version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
  jobs:
    post_install:
      - pip install poetry==2.0.1
      - poetry config virtualenvs.create false
      - poetry install -E git -E s3 --with docs

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
