version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
  jobs:
    pre_install:
      - python -m pip install poetry==2.0.1
      - poetry config virtualenvs.create false --local
      - poetry install -E git -E s3 --with docs
      - poetry export -E git -E s3 --with docs -f requirements.txt --without-hashes --output docs/requirements.txt

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
