name: Documentation
on:
  push:
    branches: [ master ]
    tags: '*'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Set up Python '3.12'
      uses: actions/setup-python@v5.4.0
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.4.0
      with:
        poetry-version: 2.0.1

    - name: Install airflow-dbt-python with Poetry
      run: poetry install -E airflow-providers --with docs

    - name: Install Graphviz
      run: sudo apt-get install graphviz

    - name: Build documentation
      run: |
        mkdir gh-pages
        touch gh-pages/.nojekyll
        cd docs/
        poetry run sphinx-build -b html . _build
        cp -r _build/* ../gh-pages/

    - name: Deploy documentation
      if: ${{ github.ref_type == 'tag' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: gh-pages
