name: PyPI deploy
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.4.0
        with:
          poetry-version: 2.0.1

      - name: Install airflow-dbt-python with Poetry
        run: poetry install

      - name: Build airflow-dbt-python with Poetry
        run: poetry build

      - name: Publish airflow-dbt-python to PyPI with Poetry
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
